name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run unit tests and generate coverage report
        run: dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Install Coveralls action
        run: dotnet tool install --global coveralls.net --version 4.0.1

      - name: Upload coverage report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: csmacnz.Coveralls --opencover -i ./millify.Tests/coverage.opencover.xml